# Question 01 : Pandas version 

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.0.3'

In [4]:
pd_housing=pd.read_csv("housing.csv",encoding="ISO-8859-1")

In [5]:
pd_housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity  
0            NEAR BAY  
1            NEAR BAY  
2            NEAR BAY  
3            NEAR BAY  
4            NEAR BAY  
...               ...  
20635          INLAND  
20636          INLAND  
20637          INLAND  
20638          INLAND  
20639          INLAND  

[20640 rows x 10 columns]

# Question 02 : number of columns

In [6]:
pd_housing.info

<bound method DataFrame.info of        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  

In [7]:
#  There are 10 columns

# Question 03 :


In [8]:
pd_housing.isnull()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0          False     False               False        False           False   
1          False     False               False        False           False   
2          False     False               False        False           False   
3          False     False               False        False           False   
4          False     False               False        False           False   
...          ...       ...                 ...          ...             ...   
20635      False     False               False        False           False   
20636      False     False               False        False           False   
20637      False     False               False        False           False   
20638      False     False               False        False           False   
20639      False     False               False        False           False   

       population  households  median_income  median_house_value  \
0           False       False          False               False   
1           False       False          False               False   
2           False       False          False               False   
3           False       False          False               False   
4           False       False          False               False   
...           ...         ...            ...                 ...   
20635       False       False          False               False   
20636       False       False          False               False   
20637       False       False          False               False   
20638       False       False          False               False   
20639       False       False          False               False   

       ocean_proximity  
0                False  
1                False  
2                False  
3                False  
4                False  
...                ...  
20635            False  
20636            False  
20637            False  
20638            False  
20639            False  

[20640 rows x 10 columns]

In [9]:
pd_housing.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [10]:
## we can see that total_bedrooms has 207 missing value

# Question 04: 

In [11]:
# unique values in ocean_proximity column are :
pd_housing["ocean_proximity"].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [12]:
# so the number is 
len(pd_housing["ocean_proximity"].unique())

5

# Question 05 :

In [13]:
pd_housing[pd_housing["ocean_proximity"]=="NEAR BAY"]["median_house_value"].describe()

count      2290.000000
mean     259212.311790
std      122818.537064
min       22500.000000
25%      162500.000000
50%      233800.000000
75%      345700.000000
max      500001.000000
Name: median_house_value, dtype: float64

In [14]:
## it's 259212.

# Question 06 :


In [21]:
# part 01 :
pd_housing["total_bedrooms"].mean()
# the average is 

537.8705525375618

In [22]:
#part 02 :
pd_housing["total_bedrooms"].fillna(pd_housing["total_bedrooms"].mean(),inplace=True)

In [23]:
pd_housing["total_bedrooms"].isnull().sum()

0

In [24]:
# part 03 :
pd_housing["total_bedrooms"].mean() 


537.8705525375617

In [25]:
# no , it hasn't changed 

# Question 07 :


In [38]:
#1)
pd_hs2=pd_housing[pd_housing["ocean_proximity"]=="ISLAND"]
pd_hs2

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [43]:
pd3=pd_hs2[['housing_median_age', 'total_rooms', 'total_bedrooms']]
pd3

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [44]:
import numpy as np
X=np.array(pd3.values)

In [45]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [67]:
XTX=np.matmul(X,X.T)


In [68]:
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [69]:
XTX_inverse=np.linalg.inv(XTX)

In [70]:
XTX_inverse


array([[-4.96451131e+09,  4.33221055e+09, -2.49341246e+09,
        -8.51337321e+09,  1.65903349e+10],
       [ 3.47335696e+09, -2.29339754e+09,  9.48896957e+08,
         6.38081159e+09, -1.22644417e+10],
       [-1.56701185e+09,  5.71843480e+08,  7.11310019e+07,
        -3.14511205e+09,  5.94553357e+09],
       [-9.00771614e+09,  8.28499475e+09, -4.98202900e+09,
        -1.52024896e+10,  2.97235715e+10],
       [ 1.73556241e+10, -1.58023656e+10,  9.42573071e+09,
         2.93839365e+10, -5.74131564e+10]])

In [71]:
y=np.array([950, 1300, 800, 1000, 1300])

In [72]:
y

array([ 950, 1300,  800, 1000, 1300])

In [76]:
w1=np.matmul(X.T,XTX_inverse)

In [77]:
w=np.matmul(w1,y)

In [78]:
w

array([ 5.1574707 , -0.09765625, -3.54003906])

In [ ]:
# the results are different from the choices , i couldn't multiply XTX_inverse by X.T but the inverse...